PR#0001: Реализован логгер с использованием паттернов Singleton и Strategy
Andriyanov322/dp-2024-lab02 pull request #1
Opened 2024-10-25 08:57 UTC by Andriyanov322

2024-10-25 08:58 UTC, Rognak commented on .github/workflows/python-tests.yml
> +      - feature  # Запускать тесты на ветке feature
Данные фильтры избыточны

2024-10-25 08:59 UTC, Rognak commented on logger/log_strategies.py
> +class LogStrategy(ABC):
Это интерфейс логгера, а не стратегии. + Необходимо вынести интерфейсы в отдельный модуль

2024-10-25 09:00 UTC, Rognak commented on logger/log_strategies.py
> +            timestamp = datetime.now().strftime("%Y-%m-%d.%H-%M-%S")
Нарушение DRY

2024-10-25 09:01 UTC, Rognak commented on logger/log_strategies.py
> +            timestamp = datetime.now().strftime("%Y-%m-%d.%H-%M-%S")
Аналогично

2024-10-25 09:01 UTC, Rognak commented on logger/logger.py
> +    def log(self, message: str, level="INFO") -> None:
уровни логирования необходимо выделить в enum

2024-10-25 09:02 UTC, vladushka2000 commented on logger/logger.py
> +class Logger(metaclass=SingletonMeta):
нету реализации интерфейса Логгера

2024-10-25 09:03 UTC, Rognak commented on logger/logger_interface.py
> +    def set_strategy(self, strategy: LogStrategy) -> None:
Названия методов должно быть приближено к решаемым задачам

2024-10-25 09:03 UTC, vladushka2000 commented on logger/log_strategies.py
> +class LogStrategy(ABC):
Мне не нравится название класса. Мы не называем сущности как паттерны, даем осмысленные названия

2024-10-25 09:04 UTC, vladushka2000 commented on logger/logger.py
> +    def log(self, message: str, level="INFO") -> None:
уровень по-умолчанию избыточен. Убрать. Пользователь явно должен задавать уровень. Сделать метод приватным

2024-10-25 09:04 UTC, Rognak commented on tests/test_logger.py
> +        os.makedirs(cls.log_directory, exist_ok=True)
Писать в реальные файлы в тестах - плохая практика
https://stackoverflow.com/questions/33650568/mock-open-function-used-in-a-class-method

2024-10-25 09:05 UTC, vladushka2000 commented on logger/logger_interface.py
> +    @abstractmethod
переименуй названия метода. Мы не завязываемся на паттернах, только на том, что делаем

2024-10-25 09:06 UTC, vladushka2000 commented on logger/logger.py
> +    def trace(self, message: str) -> None:
докстринга не полная. Нету описания аргументов

2024-10-29 06:12 UTC, Rognak requested changes
Необходимо исправить замечания

2024-10-29 07:40 UTC, vladushka2000 commented on logger/log_strategies.py
> +        log_message = f"{current_time} [{level}] {message}"
нарушен srp. Метод log отвечает за вывод лога, а не за создание сообщения

2024-10-29 07:42 UTC, vladushka2000 commented on logger/log_strategies.py
> +    def log(self, message: str, level: str) -> None:
а зачем по-сути врайтеру знать уровень лога?

2024-10-29 07:43 UTC, vladushka2000 commented on logger/log_strategies.py
> +class UpperFileLogStrategy(LogStrategy):
нарушен dry на уровне всего класса. Ты можешь его отнаследовать от FileLogStrategy

2024-10-29 14:26 UTC, vladushka2000 commented on logger/log_strategy_interface.py
> +class LogOutput(ABC):
Поменяй название на Wirter. LogOutput звучит как класс, который предназначен для хранения данных

2024-10-29 14:29 UTC, vladushka2000 commented on logger/logger_interface.py
> +class LogManager(ABC):
переименовать название LogManager в Logger. Это же интерфейс для логгера

2024-10-29 14:30 UTC, vladushka2000 commented on logger/logger_interface.py
> +    def log_event(self, message: str, level: str) -> None:
префикс _event излишен

2024-10-29 14:31 UTC, vladushka2000 commented
разнеси интерфейсы и реализации по разным папкам

2024-10-29 15:06 UTC, Andriyanov322 commented on logger/logger_interface.py
> +class LogManager(ABC):
а как назвать основной Logger тогда?

2024-10-29 15:10 UTC, Andriyanov322 commented on logger/logger_interface.py
> +class LogManager(ABC):
Или сделать LoggerInterface и Logger

2024-10-29 17:29 UTC, vladushka2000 commented on logger/implementations/logger.py
> +    _lock = Lock()
должно быть 2 лока - на создание экземпляра и запись куда-либо.
+ вынеси часть с синглтоном в отдельный класс. Ты нарушаешь srp

2024-10-29 17:30 UTC, vladushka2000 commented on logger/implementations/logger.py
> +    def log(self, message: str, level: LogLevel) -> None:
какая-то мешанина из методов _log, log, log_trace, ...
Упрости интерфейс до публичного log()

2024-10-29 17:31 UTC, vladushka2000 commented on logger/implementations/writers.py
> +from ..interfaces.writer_interface import Writer
таких импортов можно избежать, если задавать рабочую директорию для выполнения скрипта. Установи директорию как корневую папку, тогда импорты упростятся

2024-10-29 17:35 UTC, vladushka2000 commented
у тебя не для всех методов написана докстринга. Описания того, что делает метод недостаточно - необходимо описать каждый передаваемый аргумент еще

2024-10-29 18:26 UTC, vladushka2000 commented
названия коммитов неправильные.
feat(): Изменение кода программы согласно дополнительным правкам  - вообще ни о чем не говорит. И это должен быть уровень fix(). Мы же договаривались даже в аудитории, что один фикс - один коммит. Такое просто сложно проверять, когда ты все скопом засовываешь сразу.
Переделай историю коммитов с помощью ребейза

2024-10-29 18:27 UTC, vladushka2000 commented on logger/implementations/logger.py
> +    def log(self, message: str, level: LogLevel = LogLevel.INFO) -> None:
не надо делать дефолтный аргумент для уровня. Явное лучше неявного

2024-10-29 18:28 UTC, vladushka2000 commented on logger/log_levels.py
> +class LogLevel(Enum):
Добавь докстрингу для класса и описание каждого уровня лога

2024-10-29 18:29 UTC, vladushka2000 commented on logger/implementations/writers.py
> +    def _create_log_file(self, directory):
не забываем про описание передаваемых аргументов и тайп хинты. Проверь везде

2024-10-29 18:30 UTC, vladushka2000 commented
Поправь историю коммитов и мелкие замечания. В остальном все нравится)

2024-10-30 09:09 UTC, vladushka2000 commented
все круто, все супер, засчитал

2024-10-30 09:10 UTC, vladushka2000 approved these changes

2024-10-31 06:47 UTC, Rognak commented on logger/implementations/writers.py
> +class ConsoleWriter(Writer):
IWriter

2024-10-31 07:44 UTC, merged